### ISSUE TITLE
Sandstorm DokuWiki support?

### ISSUE THREAD

**Issue by sraimund** [turnermm/ckgedit#465]
When I manually install your plugin in Sandstorm's DokuWiki via uploading a tar.gz file, I get an empty screen when editing a page, and the following error message appear in the console:

In Chromium:
```
VM315 config.js:1 Uncaught DOMException: Blocked a frame with origin "https://ui-0090c6b1e2f2890229870157242e7337.oasis.sandstorm.io" from accessing a cross-origin frame.
    at a.CKEDITOR.editorConfig (https://ui-0090c6b1e2f2890229870157242e7337.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/config.js?t=H4P6:1:7521)
    at k (https://ui-0090c6b1e2f2890229870157242e7337.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:246:276)
    at Object.<anonymous> (https://ui-0090c6b1e2f2890229870157242e7337.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:246:479)
    at Object.callback (https://ui-0090c6b1e2f2890229870157242e7337.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:236:26)
    at g (https://ui-0090c6b1e2f2890229870157242e7337.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:234:33)
    at Array.n (https://ui-0090c6b1e2f2890229870157242e7337.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:234:188)
    at p (https://ui-0090c6b1e2f2890229870157242e7337.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:234:272)
    at https://ui-0090c6b1e2f2890229870157242e7337.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:235:173
```

In Firefox:
``` 
SecurityError: Permission denied to access property "JSINFO" on cross-origin object config.js:1
    editorConfig https://ui-fad1c06118155bf14226d345457c9a51.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/config.js?t=H4P6:1 
	k https://ui-fad1c06118155bf14226d345457c9a51.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:246 
	k https://ui-fad1c06118155bf14226d345457c9a51.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:246 
	callback https://ui-fad1c06118155bf14226d345457c9a51.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:236 
	g https://ui-fad1c06118155bf14226d345457c9a51.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:234 
	n https://ui-fad1c06118155bf14226d345457c9a51.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:234 
	p https://ui-fad1c06118155bf14226d345457c9a51.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:234 
	onload https://ui-fad1c06118155bf14226d345457c9a51.oasis.sandstorm.io/lib/plugins/ckgedit/ckeditor/ckeditor.js:235 
```

I tried it with an older released version (ckgedit-cked_f4.7.tar.gz), as their DokuWiki version is of 2017, and the latest version (ckgedit-4.9.tar.gz), but both ended in the error described above.

To reproduce this issue, follow these steps:
- https://sandstorm.io/ > Online Demo
- click on "Start >>"
- Install ... from app market
- Choose DokuWiki & click on Install
- Create new wiki
- Admin > Extension Manager > Manual Install > Upload and install extension (browse for tar.gz file)
- Navigate to the welcome page (e.g. via Sitemap) and click on "Edit this page"

I chose manual install because installing plugins via the repository does not seem to work:
https://github.com/sandstorm-io/sandstorm/issues/1359

**Comment by turnermm** [comment]
Nothing I can do about this.

**Comment by turnermm** [comment]
You will have to take this up with Sandstorm, which has such a restrictive envirornment that it sees threats where threats don't exist.

**Comment by sraimund** [comment]
OK, thanks for investigating.
