### ISSUE TITLE
Error: Call to undefined function symlink()

### ISSUE THREAD

**Issue by akhzz905** [turnermm/ckgedit#710]
After install CKGEdit plugin, all of the pages shows below.
```
Error: Call to undefined function symlink()
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the ckgedit plugin.
More info has been written to the DokuWiki error log.
```
In error log, it shows
```
2024-01-29 04:57:48	/pathToWebsite/lib/plugins/ckgedit/action/meta.php(622)	Error: Call to undefined function symlink()
  #0 /pathToWebsite/lib/plugins/ckgedit/action/meta.php(817): action_plugin_ckgedit_meta->check_userfiles()
  #1 /pathToWebsite/inc/Extension/EventHandler.php(80): action_plugin_ckgedit_meta->file_type()
  #2 /pathToWebsite/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
  #3 /pathToWebsite/inc/Extension/Event.php(132): dokuwiki\Extension\Event->advise_before()
  #4 /pathToWebsite/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
  #5 /pathToWebsite/doku.php(120): dokuwiki\Extension\Event::createAndTrigger()
  #6 {main}
```
My system is Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-94-generic x86_64), and run dokuwiki 2023-04-04a "Jack Jackrum" with PHP8.0

**Comment by reetp** [comment]
And it turns out that the reason is that the symlinks are disabled in your PHP setup, probably for security.

I guess this could be disabled?

cat ckgedit/conf/default.php

`$conf['no_symlinks'] = 0;`

I'm not sure on the best course of action here.
