### ISSUE TITLE
Error: Call to undefined function symlink()

### ISSUE THREAD

**Issue by he110-c0de** [turnermm/ckgedit#716]
Error: Call to undefined function symlink()

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the ckgedit plugin.

More info has been written to the DokuWiki error log.

Looks like some web hosting do not allow to call symlink.

**Comment by psychoberries** [comment]
Same issue here, while testing on byet.host/free-hosting
Installing ckgedit causes the whole dokuwiki to fail with the following error:
`Error: Call to undefined function symlink()

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the ckgedit plugin.

More info has been written to the DokuWiki error log.`

I wouldn't not know what to make of the DokuWiki error log itself:
`2024-09-15 06:15:17	/home/volNumber/byethost7.com/accountNumber/domain.com/htdocs/dkwk/lib/plugins/ckgedit/action/meta.php(622)	Error: Call to undefined function symlink()
  #0 /home/volNumber/byethost7.com/accountNumber/domain.com/htdocs/dkwk/lib/plugins/ckgedit/action/meta.php(817): action_plugin_ckgedit_meta->check_userfiles()
  #1 /home/volNumber/byethost7.com/accountNumber/domain.com/htdocs/dkwk/inc/Extension/EventHandler.php(80): action_plugin_ckgedit_meta->file_type(Object(dokuwiki\Extension\Event), NULL)
  #2 /home/volNumber/byethost7.com/accountNumber/domain.com/htdocs/dkwk/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
  #3 /home/volNumber/byethost7.com/accountNumber/domain.com/htdocs/dkwk/inc/Extension/Event.php(133): dokuwiki\Extension\Event->advise_before(false)
  #4 /home/volNumber/byethost7.com/accountNumber/domain.com/htdocs/dkwk/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger(NULL, false)
  #5 /home/volNumber/byethost7.com/accountNumber/domain.com/htdocs/dkwk/doku.php(125): dokuwiki\Extension\Event::createAndTrigger('DOKUWIKI_STARTE...', Array)
  #6 {main}`

**Comment by reetp** [comment]
Duplicate of #710
